## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [2]:
import sys
import numpy as np

In [3]:
n = 3

In [4]:
2 ** 3

8

In [5]:
x = 5

In [6]:
np.int8   

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

#### What is an array?

<p> An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
</p>

<p style="color: blue"> numpy.array (object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None) </p>

In [7]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

In [8]:
a = np.array([1, 2, 3, 4])

In [9]:
a[0], a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1: 3]

array([2, 3])

In [12]:
a[-1::-1]

array([4, 3, 2, 1])

In [13]:
a[1:-1]

array([2, 3])

In [14]:
a[::2]

array([1, 3])

In [15]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :1])

[['a']
 ['d']
 ['g']]


Obs.: O ultimo não vai aparecer

In [16]:
b = np.array([0, .5, 1, 1.5, 2])

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [19]:
b[[0, 2, -1]]
# Usando varios index 


array([0., 1., 2.])

### Array Types

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a.dtype

dtype('int64')

In [22]:
b.dtype

dtype('float64')

In [23]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [24]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [25]:
c = np.array(['a', 'b', 'c'])

In [26]:
c.dtype

dtype('<U1')

O resultado, dtype('<U1'), significa que o tipo de dados de c é Unicode (U) e cada elemento ocupa 1 byte na memória (1). Essa é uma representação interna do NumPy para strings Unicode de tamanho fixo de 1 byte.

In [27]:
d = np.array([{'a': 1}, sys])

In [28]:
d.dtype

dtype('O')

O primeiro elemento é um dicionário Python {'a': 1}, e o segundo elemento é a variável sys, que provavelmente é um módulo do Python. Ao executar d.dtype, você obtém dtype('O'), o que significa que o tipo de dados de d é "objeto" (object).

O tipo de dados 'O' no NumPy é usado para representar objetos Python que não se encaixam facilmente em tipos de dados NumPy regulares.






### Dimensions and Shapes