## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [14]:
import sys
import numpy as np

In [15]:
n = 3

In [16]:
2 ** 3

8

In [17]:
x = 5

In [18]:
np.int8   

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

#### What is an array?

<p> An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
</p>

<p style="color: blue"> numpy.array (object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None) </p>

In [19]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

In [20]:
a = np.array([1, 2, 3, 4])

In [21]:
a[0], a[1]

(1, 2)

In [22]:
a[0:]

array([1, 2, 3, 4])

In [23]:
a[1: 3]

array([2, 3])

In [24]:
a[-1::-1]

array([4, 3, 2, 1])

In [25]:
a[1:-1]

array([2, 3])

In [26]:
a[::2]

array([1, 3])

In [27]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :1])

[['a']
 ['d']
 ['g']]


Obs.: O ultimo não vai aparecer

In [28]:
b = np.array([0, .5, 1, 1.5, 2])

In [29]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)