## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [28]:
import sys
import numpy as np

In [29]:
n = 3

In [30]:
2 ** 3

8

In [31]:
x = 5

In [32]:
np.int8   

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

#### What is an array?

<p> An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
</p>

In [33]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

<p style="color: blue"> numpy.array (object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None) </p>

In [34]:
a = np.array([1, 2, 3, 4])

In [35]:
a[0], a[1]

(1, 2)

In [36]:
a[0:]

array([1, 2, 3, 4])

In [37]:
a[1: 3]

array([2, 3])

In [38]:
a[-1::-1]

array([4, 3, 2, 1])

In [39]:
a[1:-1]

array([2, 3])

In [40]:
a[::2]

array([1, 3])

In [56]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 624, in change_attr_expression
    value = eval(expression, frame.f_globals, frame.f_locals)
  File "<string>", line 1, in <module>
NameError: name 'array' is not defined


[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Obs.: O ultimo não vai aparecer

In [42]:
b = np.array([0, .5, 1, 1.5, 2])

In [43]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [44]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [45]:
b[[0, 2, -1]]
# Usando varios index 


array([0., 1., 2.])

### Array Types

In [46]:
a

array([1, 2, 3, 4])

In [47]:
a.dtype

dtype('int64')

In [48]:
b.dtype

dtype('float64')

In [49]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [50]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [51]:
c = np.array(['a', 'b', 'c'])

In [52]:
c.dtype

dtype('<U1')

O resultado, dtype('<U1'), significa que o tipo de dados de c é Unicode (U) e cada elemento ocupa 1 byte na memória (1). Essa é uma representação interna do NumPy para strings Unicode de tamanho fixo de 1 byte.

In [57]:
d = np.array([{'a': 1}, sys])

In [54]:
d.dtype

dtype('O')

O primeiro elemento é um dicionário Python {'a': 1}, e o segundo elemento é a variável sys, que provavelmente é um módulo do Python. Ao executar d.dtype, você obtém dtype('O'), o que significa que o tipo de dados de d é "objeto" (object).

O tipo de dados 'O' no NumPy é usado para representar objetos Python que não se encaixam facilmente em tipos de dados NumPy regulares.






### Dimensions and Shapes

In [66]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

# Deve ser homogêneo, ou seja, todos os objetos devem ser do mesmo tipo.

In [67]:
A.shape

(2, 3)