## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [110]:
import sys
import numpy as np

In [111]:
n = 3

In [112]:
2 ** 3

8

In [113]:
x = 5

In [114]:
np.int8   

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

#### What is an array?

<p> An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
</p>

In [115]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

<p style="color: blue"> numpy.array (object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None) </p>

In [116]:
a = np.array([1, 2, 3, 4])

In [117]:
a[0], a[1]

(1, 2)

In [118]:
a[0:]

array([1, 2, 3, 4])

In [119]:
a[1: 3]

array([2, 3])

In [120]:
a[-1::-1]

array([4, 3, 2, 1])

In [121]:
a[1:-1]

array([2, 3])

In [122]:
a[::2]

array([1, 3])

In [123]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Obs.: O ultimo não vai aparecer

In [124]:
b = np.array([0, .5, 1, 1.5, 2])

In [125]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [126]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [127]:
b[[0, 2, -1]]
# Usando varios index 


array([0., 1., 2.])

### Array Types

In [128]:
a

array([1, 2, 3, 4])

In [129]:
a.dtype

dtype('int64')

In [130]:
b.dtype

dtype('float64')

In [131]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [132]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [133]:
c = np.array(['a', 'b', 'c'])

In [134]:
c.dtype

dtype('<U1')

O resultado, dtype('<U1'), significa que o tipo de dados de c é Unicode (U) e cada elemento ocupa 1 byte na memória (1). Essa é uma representação interna do NumPy para strings Unicode de tamanho fixo de 1 byte.

In [135]:
d = np.array([{'a': 1}, sys])

In [136]:
d.dtype

dtype('O')

O primeiro elemento é um dicionário Python {'a': 1}, e o segundo elemento é a variável sys, que provavelmente é um módulo do Python. Ao executar d.dtype, você obtém dtype('O'), o que significa que o tipo de dados de d é "objeto" (object).

O tipo de dados 'O' no NumPy é usado para representar objetos Python que não se encaixam facilmente em tipos de dados NumPy regulares.






### Dimensions and Shapes

In [137]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

# Deve ser homogêneo, ou seja, todos os objetos devem ser do mesmo tipo.

In [138]:
A.shape

(2, 3)

In [139]:
A.ndim

2

In [140]:
A.size

6

In [141]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [142]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [143]:
B.ndim

3

In [144]:
B.size

12

If the shape isn't consistent, it'll just fall back  to regular Python objects:

In [147]:
import sys
import numpy as np

C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
])

/tmp/ipykernel_8744/781096257.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [149]:
C.dtype

dtype('O')

In [150]:
C.shape

(2,)

In [151]:
C.size

2

In [153]:
type(C[0])

list

## Indexing and Slicing of Matrices

In [155]:
# Square matrix
A = np.array([
#. 0. 1. 2
    [1,2,3], # 0
    [4,5,6], #1
    [7,8,9] #2
])

In [156]:
A[1]

array([4, 5, 6])

In [158]:
A[1][0]

4

In [159]:
#A[d1, d2, d3, d4]


In [165]:
A[1, 0]
#ou A[1][0]

4

In [167]:
A[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [169]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [170]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
A[1]=np.array([10,10,10])

In [173]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [174]:
A[2]=99
#Vai repetir para as três colunas.

In [175]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])