## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [1]:
import sys
import numpy as np

In [2]:
n = 3

In [3]:
2 ** 3

8

In [4]:
x = 5

In [5]:
np.int8   

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

#### What is an array?

<p> An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
</p>

In [6]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

<p style="color: blue"> numpy.array (object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None) </p>

In [7]:
a = np.array([1, 2, 3, 4])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a[1: 3]

array([2, 3])

In [11]:
a[-1::-1]

array([4, 3, 2, 1])

In [12]:
a[1:-1]

array([2, 3])

In [13]:
a[::2]

array([1, 3])

In [14]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Obs.: O ultimo não vai aparecer

In [15]:
b = np.array([0, .5, 1, 1.5, 2])

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [18]:
b[[0, 2, -1]]
# Usando varios index 


array([0., 1., 2.])

### Array Types

In [19]:
a

array([1, 2, 3, 4])

In [20]:
a.dtype

dtype('int64')

In [21]:
b.dtype

dtype('float64')

In [22]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [23]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [24]:
c = np.array(['a', 'b', 'c'])

In [25]:
c.dtype

dtype('<U1')

O resultado, dtype('<U1'), significa que o tipo de dados de c é Unicode (U) e cada elemento ocupa 1 byte na memória (1). Essa é uma representação interna do NumPy para strings Unicode de tamanho fixo de 1 byte.

In [26]:
d = np.array([{'a': 1}, sys])

In [27]:
d.dtype

dtype('O')

O primeiro elemento é um dicionário Python {'a': 1}, e o segundo elemento é a variável sys, que provavelmente é um módulo do Python. Ao executar d.dtype, você obtém dtype('O'), o que significa que o tipo de dados de d é "objeto" (object).

O tipo de dados 'O' no NumPy é usado para representar objetos Python que não se encaixam facilmente em tipos de dados NumPy regulares.






### Dimensions and Shapes

In [28]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

# Deve ser homogêneo, ou seja, todos os objetos devem ser do mesmo tipo.

In [29]:
A.shape

(2, 3)

In [30]:
A.ndim

2

In [31]:
A.size

6

In [32]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [33]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [34]:
B.ndim

3

In [35]:
B.size

12

If the shape isn't consistent, it'll just fall back  to regular Python objects:

In [36]:
import sys
import numpy as np

C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
])

/tmp/ipykernel_10970/781096257.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [37]:
C.dtype

dtype('O')

In [38]:
C.shape

(2,)

In [39]:
C.size

2

In [40]:
type(C[0])

list

## Indexing and Slicing of Matrices

In [41]:
# Square matrix
A = np.array([
#. 0. 1. 2
    [1,2,3], # 0
    [4,5,6], #1
    [7,8,9] #2
])

In [42]:
A[1]

array([4, 5, 6])

In [43]:
A[1][0]

4

In [44]:
#A[d1, d2, d3, d4]


In [45]:
A[1, 0]
#ou A[1][0]

4

In [46]:
A[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
A[1]=np.array([10,10,10])

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [52]:
A[2]=99
#Vai repetir para as três colunas.

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary statistics

In [54]:
a = np.array([1,2,3,4])

In [55]:
a.sum()

10

In [58]:
a.mean()

2.5

In [ ]:
a.std()