## Introdução ao Numpy.
 NumPy(Numerical Python) é um dos pacotes principais para computação numérica em Python, Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas.
 Por que Numpy é tão importante? No python, o processamento numérico puro é muito lento. Numpy é uma biblioteca de processamento numérico muito eficiente, que oferece uma API, na qual trabalhára-se apenas com o código Python. 

In [7]:
import sys
import numpy as np

In [8]:
n = 3

In [9]:
2 ** 3

8

In [10]:
x = 5

In [11]:
np.int8

numpy.int8

Eu posso criar numeros e controlar a quantidade de bits

### Basic Numpy Arrays

In [12]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

In [15]:
a = np.array([1, 2, 3, 4])

In [16]:
a[0], a[1]

(1, 2)

In [17]:
a[0:]

array([1, 2, 3, 4])

In [18]:
a[1: 3]

array([2, 3])

In [28]:
a[-1::-1]

array([4, 3, 2, 1])

In [29]:
a[1:-1]

array([2, 3])

In [30]:
a[::2]

array([1, 3])

In [32]:
b

NameError: name 'b' is not defined